set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN C17 [get_ports CLK]
set_property PACKAGE_PIN B17 [get_ports DATA]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports DATA]
set_property IOSTANDARD LVCMOS33 [get_ports {BLU[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BLU[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BLU[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BLU[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GRN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GRN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GRN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GRN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[0]}]
set_property PACKAGE_PIN N18 [get_ports {BLU[0]}]
set_property PACKAGE_PIN L18 [get_ports {BLU[1]}]
set_property PACKAGE_PIN K18 [get_ports {BLU[2]}]
set_property PACKAGE_PIN J18 [get_ports {BLU[3]}]
set_property PACKAGE_PIN J17 [get_ports {GRN[0]}]
set_property PACKAGE_PIN H17 [get_ports {GRN[1]}]
set_property PACKAGE_PIN G17 [get_ports {GRN[2]}]
set_property PACKAGE_PIN D17 [get_ports {GRN[3]}]
set_property PACKAGE_PIN G19 [get_ports {RED[0]}]
set_property PACKAGE_PIN H19 [get_ports {RED[1]}]
set_property PACKAGE_PIN J19 [get_ports {RED[2]}]
set_property PACKAGE_PIN N19 [get_ports {RED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports HSync]
set_property PACKAGE_PIN P19 [get_ports HSync]
set_property IOSTANDARD LVCMOS33 [get_ports VSync]
set_property PACKAGE_PIN R19 [get_ports VSync]

set_property PACKAGE_PIN V17 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports RST]

set_property IOSTANDARD LVCMOS33 [get_ports {direct[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {direct[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gamestate[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gamestate[0]}]
set_property PACKAGE_PIN P3 [get_ports {direct[1]}]
set_property PACKAGE_PIN U3 [get_ports {direct[0]}]
set_property PACKAGE_PIN L1 [get_ports {gamestate[1]}]
set_property PACKAGE_PIN P1 [get_ports {gamestate[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {scorel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scorel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scorel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scorel[3]}]
set_property PACKAGE_PIN U16 [get_ports {scorel[0]}]
set_property PACKAGE_PIN E19 [get_ports {scorel[1]}]
set_property PACKAGE_PIN U19 [get_ports {scorel[2]}]
set_property PACKAGE_PIN V19 [get_ports {scorel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scorem[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scorem[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scorem[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scorem[3]}]
set_property PACKAGE_PIN W18 [get_ports {scorem[0]}]
set_property PACKAGE_PIN U15 [get_ports {scorem[1]}]
set_property PACKAGE_PIN U14 [get_ports {scorem[2]}]
set_property PACKAGE_PIN V14 [get_ports {scorem[3]}]

set_property PACKAGE_PIN V16 [get_ports mist]
set_property IOSTANDARD LVCMOS33 [get_ports mist]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
